version: 1.0.{build}

platform: Any CPU

configuration: Release

before_build:
  - nuget restore .\src\Expressior.sln

environment:
  dynamo_solution: src/Expressior.sln
  oauth_access_token:
    secure: 14B2LfzdzmTNRCadtOW73/mofQniTe49NA71lH65TSq8uLPeTKlIu/o2FVUOisAc

build_script:
  - msbuild %dynamo_solution%

on_success:  
 - ps: >- 
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {	
      git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
      git config --global credential.helper store
    }  


test: off
