version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: x64
before_build:
  - nuget restore .\src\Expressior.sln

build:
  project: src/Expressior.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - jiafeng5513@outlook.com
  - 1535432383@qq.com
  subject: '[Ci Merge Control]<VisualScripts>'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
on_success:  
 - ps: >- 
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {	
      git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
      git config --global credential.helper store
    }  
test: off